HeatTemplateFormatVersion: '2012-12-12'
Description: "Create an Hadoop Cluster. "
Parameters: 
    KeyName: 
        Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance. "
        Type: "String"
        Default: "richardr_on_nectar"
    InstanceType:
        Description: "The size of the VM. "
        Type: String
        Default: "m1.small"
        AllowedValues:
            - m1.small
            - m1.medium
            - m1.large
            - m1.xlarge
            - m1.xxlarge
    ImageId:
        Description: "The base VM image used to build the cluster. "
        Type: String
        Default: "96761a90-635b-4718-8deb-f4ff57632db4"
    AvailabilityZone: 
        Description: "Location of the running cluster. "
        Type: String
        Default: "sa"
        AllowedValues:
            - NCI
            - melbourne
            - melbourne-np
            - melbourne-qh2
            - qld
            - sa
Resources: 
    # http://docs.openstack.org/developer/heat/template_guide/cfn.html#AWS::EC2::SecurityGroup
    DefaultSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Standard firewall rules
            SecurityGroupIngress:
                - {IpProtocol: icmp, FromPort: '-1', ToPort: '-1', CidrIp : 0.0.0.0/0}
                - {IpProtocol: tcp, FromPort: '22', ToPort: '22', CidrIp: 0.0.0.0/0}
                - {IpProtocol: tcp, FromPort: '80', ToPort: '80', CidrIp: 0.0.0.0/0}
                - {IpProtocol: tcp, FromPort: '443', ToPort: '443', CidrIp: 0.0.0.0/0}
    MemberSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Use a dummy security group as a tag signifying belonging to the cluster.
    ClusterSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Cluster commmunications allowed only from cluster members
            SecurityGroupIngress:
                - {IpProtocol: tcp, FromPort: '1', ToPort: '65535', SourceSecurityGroupName: {Ref: MemberSecurityGroup}}
    WebManagementSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Expose the Hadoop web-based management interfaces.
            SecurityGroupIngress:
                - {IpProtocol: tcp, FromPort: '50070', ToPort: '50070', CidrIp: 0.0.0.0/0}
                - {IpProtocol: tcp, FromPort: '50030', ToPort: '50030', CidrIp: 0.0.0.0/0}
                - {IpProtocol: tcp, FromPort: '50060', ToPort: '50060', CidrIp: 0.0.0.0/0}
                - {IpProtocol: tcp, FromPort: '50075', ToPort: '50075', CidrIp: 0.0.0.0/0}
                - {IpProtocol: tcp, FromPort: '50090', ToPort: '50090', CidrIp: 0.0.0.0/0}
                - {IpProtocol: tcp, FromPort: '60010', ToPort: '60010', CidrIp: 0.0.0.0/0}
    # http://docs.openstack.org/developer/heat/template_guide/cfn.html#AWS::EC2::Instance
    HadoopMaster: 
        Type: "AWS::EC2::Instance"
        Properties: 
            KeyName: {Ref: KeyName}
            ImageId: {Ref: ImageId}
            InstanceType: {Ref: InstanceType}
            AvailabilityZone: {Ref: AvailabilityZone}
            SecurityGroups: 
                - {Ref: DefaultSecurityGroup}
                - {Ref: MemberSecurityGroup}
                - {Ref: ClusterSecurityGroup}
                - {Ref: WebManagementSecurityGroup}
            UserData: 
                Fn::Base64:
                    Fn::Replace:
                      - _tm_username: {Ref: TileMillUserName}
                        _tm_password: {Ref: TileMillPassword}
                        _tm_dbusername: {Ref: DBUsername}
                        _tm_dbpassword: {Ref: DBPassword}
                        _tm_timezone: {Ref: Timezone}
                        _POSTGRESDIR: /mnt/var/lib
                      - |
                        #!/bin/bash -v
                        apt-get install -y git
                        cd /tmp
                        git clone https://github.com/stevage/tilemill-server
                        cd tilemill-server
                        export tm_dbusername='_tm_dbusername'
                        export tm_dbpassword='_tm_dbpassword'
                        export tm_username='_tm_username'
                        export tm_password='_tm_password'
                        export tm_timezone='_tm_timezone'
                        export POSTGRESDIR='_POSTGRESDIR'
                              ./install.sh
Outputs: 
    InstanceIp: 
        Value: 
            Fn::Join: 
                - ""
                - 
                    - "ssh hadoop-admin@"
                    - 
                        Fn::GetAtt: 
                            - "HadoopMaster"
                            - "PublicIp"
        Description: "My ssh command"
