HeatTemplateFormatVersion: '2012-12-12'
Description: "Create an Hadoop Cluster. "
Parameters: 
    KeyName: 
        Description: "Name of an existing EC2 KeyPair to enable SSH access to the instance. "
        Type: "String"
    InstanceType:
        Description: "The size of the VM. "
        Type: String
        Default: "m1.small"
        AllowedValues:
            - m1.small
            - m1.medium
            - m1.large
            - m1.xlarge
            - m1.xxlarge
    ImageId:
        Description: "The base VM image used to build the cluster. "
        Type: String
        Default: "96761a90-635b-4718-8deb-f4ff57632db4"
Resources: 
    MyInstance: 
        Type: "AWS::EC2::Instance"
        Properties: 
            KeyName: {Ref: KeyName}
            ImageId: {Ref: ImageId}
            InstanceType: {Ref: InstanceType}
            UserData: 
                Fn::Base64: "80"
Outputs: 
    InstanceIp: 
        Value: 
            Fn::Join: 
                - ""
                - 
                    - "ssh ec2-user@"
                    - 
                        Fn::GetAtt: 
                            - "MyInstance"
                            - "PublicIp"
        Description: "My ssh command"
